### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by jmwang0117** [dizcza/pytorch-sm30-docker#2]
thanks for your work
What is the python version in this Docker?

**Comment by jmwang0117** [comment]
achieve

**Comment by dizcza** [comment]
> thanks for your work What is the python version in this Docker?

https://github.com/dizcza/pytorch-sm30-docker/blob/2bcffa5d47993ab00544bc171c44ffa69c5e7786/Dockerfile#L23C1-L23C23

```
ENV PYTHON_VERSION 3.9
```
