### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Mrdigs** [dizcza/pytorch-sm30-docker#3]
Just a big thank you from me, that's all. I've been trying to get a working GPU accelerated Pytorch install for my sm_30 card for days and have had a total nightmare. 

Just getting a working CUDA 10.2 installation on my Ubuntu 22.04 O/S has been a nightmare enough with dependency issues from both the Ubuntu and NVIDIA packages, which I could only resolve by using the 18.04 repo and a custom built dummy package to trick it into being happy with my driver and X server versions.

Then, having been reassured from multiple sources that building Pytorch from source for CUDA 10.2 with an sm_30 GPU was possible and finding out it's not as straight forward as I was lead to believe and a lot of misinformation on exactly what version supports it (if any), I came across your project, tested the image and it worked, proving to me that it WAS possible just at the point I was about to give up.

I'm not using your Docker image, but the Dockerfile has given me the information that I need  - basically that I can build NCCL for an sm_30 architecture and then build Pytorch with USE_SYSTEM_NCCL to avoid the compilation error I was getting due to the lack of the __funnelshift_r() intrinsic in 3.0 GPUS.

I don't know how much work you put into this, but there's at least one person here who appreciates your effort because I have been pulling my hair out trying to put this jigsaw puzzle together.

I might be jinxing myself as the build is still working and I have had so many instances where I thought I'd managed to get somewhere only to be presented with another compilation error, and I still don't understand how CuDNN can work because NVIDIAs support matrix says "no" for sm_30, but it has at least allowed me to move forward on to my next challenge.

So - thank you!

**Comment by dizcza** [comment]
Glad to hear that my efforts saved someone else's time!
